#!/usr/bin/env ruby
# frozen_string_literal: true

lib_dir = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(lib_dir) unless $LOAD_PATH.include?(lib_dir)

require 'thor'
require 'eidos/cli/world'
require 'eidos/cli/bible'
require 'eidos/cli/canon'
require 'eidos/cli/produce'
require 'eidos/cli/translate'
require 'eidos/cli/publish'
require 'eidos/version'

module Eidos
  module CLI
    # Top-level CLI router. Delegates to existing subcommand classes.
    class Main < Thor
      desc 'world SUBCOMMAND ...ARGS', 'Manage worlds'
      subcommand 'world', Eidos::CLI::World

      desc 'bible SUBCOMMAND ...ARGS', 'Manage the Story Bible'
      subcommand 'bible', Eidos::CLI::Bible

      desc 'canon SUBCOMMAND ...ARGS', 'Manage canon versioning'
      subcommand 'canon', Eidos::CLI::Canon

      desc 'produce SUBCOMMAND ...ARGS', 'Generate content'
      subcommand 'produce', Eidos::CLI::Produce

      desc 'translate SUBCOMMAND ...ARGS', 'Translate content'
      subcommand 'translate', Eidos::CLI::Translate

      desc 'publish SUBCOMMAND ...ARGS', 'Publish content'
      subcommand 'publish', Eidos::CLI::Publish

      desc 'version', 'Show version'
      def version
        puts "eidos #{Eidos::VERSION}"
      end

      map %w[--version -v] => :version
    end
  end
end

Eidos::CLI::Main.start(ARGV)
